# docker-compose.yml
version: '3'

services:
  api-gateway:
    container_name: qultivar-api-gateway
    image: therudeway.com/qultivar/api-gateway:latest
    pull_policy: never
    networks:
      frontend:
        aliases:
          - api-gateway
      backend:
        aliases:
          - api-gateway
    hostname: api-gateway.qultivar.therudeway.com
    ports:
      - "8080:8080"
    environment:
      DOMAIN_NAME: qultivar.therudeway.com
    volumes:
      - ./api-gateway/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./api-gateway/html/:/usr/share/nginx/html/

  api-service:
    container_name: qultivar-api-service
    image: therudeway.com/qultivar/api-service:latest
    pull_policy: never
    hostname: api-service.qultivar.therudeway.com
    networks:
      backend:
        aliases:
          - api-service

  db-service:
    container_name: qultivar-db-service
    image: therudeway.com/qultivar/db-service:latest
    pull_policy: never
    hostname: db-service.qultivar.therudeway.com
    networks:
      backend:
        aliases:
          - db-service
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres-db-username
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-db-password
    volumes:
      - qultivar-data-volume:/var/lib/postgresql/data
    secrets:
      - postgres-db-username
      - postgres-db-password

  auth-service:
    container_name: qultivar-auth-service
    image: therudeway.com/qultivar/auth-service:latest
    pull_policy: never
    hostname: auth-service.qultivar.therudeway.com
    networks:
      backend:
        aliases:
          - auth-service

  feed-service:
    container_name: qultivar-feed-service
    image: therudeway.com/qultivar/feed-service:latest
    pull_policy: never
    depends_on:
      - db-service
    hostname: feed-service.qultivar.therudeway.com
    networks:
      backend:
        aliases:
          - feed-service
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db-service:5432/qultivar_feed_service

  user-service:
    container_name: qultivar-user-service
    image: therudeway.com/qultivar/user-service:latest
    pull_policy: never
    depends_on:
      - db-service
    hostname: user-service.qultivar.therudeway.com
    networks:
      backend:
        aliases:
          - user-service
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db-service:5432/qultivar_user_service

  media-service:
    container_name: qultivar-media-service
    image: therudeway.com/qultivar/media-service:latest
    pull_policy: never
    hostname: media-service.qultivar.therudeway.com
    networks:
      backend:
        aliases:
          - media-service

  qultivar-gui:
    container_name: qultivar-gui
    image: therudeway.com/qultivar/qultivar-gui:latest
    pull_policy: never
    hostname: qultivar-gui.qultivar.therudeway.com
    ports:
      - 3000:3000
    networks:
      frontend:
        aliases:
          - qultivar-gui
    volumes:
      - ./qultivar-gui/src:/app/src


networks:
  frontend:
  backend:


volumes:
  qultivar-data-volume:
    name: qultivar-data-volume


secrets:
  postgres-db-username:
    file: ./secrets/postgres-db-username
  postgres-db-password:
    file: ./secrets/postgres-db-password
  qultivar-db-username:
    file: ./secrets/qultivar-db-username
  qultivar-db-password:
    file: ./secrets/qultivar-db-password
